version: "3.9"

services:
  bot:
    build: .
    environment:
      - DISCORD_TOKEN=
      - LOG_CHANNEL_ID=
      - RR_CHANNEL_ID=
      - T1_ROLE_ID=
      - T2_ROLE_ID=
      - T3_ROLE_ID=
    restart: always
    volumes:
      - type: bind
        source: src/gw2/builds.json
        target: /bot/gw2/builds.json