version: "3.9"

services:
  bot:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DISCORD_TOKEN=
      - DATABASE_URL=postgresql+asyncpg://crossroads:crossroads@db/crossroads
    restart: always

  db:
    image: postgres:15.2
    environment:
      - POSTGRES_USER=crossroads
      - POSTGRES_PASSWORD=crossroads
      - POSTGRES_DB=crossroads
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 30s
      retries: 5
    restart: always

volumes:
  db-data: